export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_LOADING_CHARACTER_LIST = "SET_LOADING_CHARACTER_LIST";
export const SET_CHARACTER_LIST = "SET_CHARACTER_LIST";
export const SET_SELECTED_CHARACTER = "SET_SELECTED_CHARACTER";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const SET_TOTAL_COUNT = "SET_TOTAL_COUNT";
export const SET_LOADING_SUGGESTION_LIST = "SET_LOADING_SUGGESTION_LIST";
export const SET_SUGGESTION_LIST = "SET_SUGGESTION_LIST";
